[package]
name = "hecto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]

[dependencies]
crossterm = "0.26"
[[bin]]
name = "main"
path = "src/main.rs"